# Generated by Django 4.2.7 on 2023-12-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tipo_pago',
            field=models.TextField(choices=[['Cr', 'Contrareembolso'], ['T', 'Tarjeta']], default='Cr', verbose_name=''),
            preserve_default=False,
        ),
    ]
