# Generated by Django 4.1.13 on 2023-12-03 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reclamaciones", "0002_reclamacion_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="reclamacion",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
