# Generated by Django 4.2.7 on 2023-12-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reclamaciones", "0003_reclamacion_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reclamacion",
            name="username",
            field=models.CharField(max_length=200, null=True, verbose_name="Username"),
        ),
    ]
