# Generated by Django 4.2.7 on 2023-11-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200)),
                ('product_type', models.CharField(choices=[('RU', 'RUEDAS'), ('MO', 'MOTOR'), ('FR', 'FRENOS'), ('FI', 'FILTROS'), ('EM', 'EMBRAGUE'), ('ES', 'ESCAPE'), ('MA', 'MANILLAR'), ('OT', 'OTROS')], default='OT', max_length=255, verbose_name='Tipo de producto')),
                ('producer', models.CharField(choices=[('KA', 'KAWASAKI'), ('HO', 'HONDA'), ('YA', 'YAMAHA'), ('DU', 'DUCATI'), ('KY', 'KYMCO'), ('OT', 'OTROS')], default='OT', max_length=255, verbose_name='fabricante')),
                ('image', models.ImageField(blank=True, upload_to='static/images')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='shop_produc_id_f21274_idx'), models.Index(fields=['name'], name='shop_produc_name_a2070e_idx'), models.Index(fields=['-created'], name='shop_produc_created_ef211c_idx')],
            },
        ),
    ]
