# Generated by Django 4.2.7 on 2023-12-04 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motosaurio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="miusuario",
            name="codigo",
            field=models.IntegerField(
                default=41012,
                validators=[django.core.validators.MaxValueValidator(99999)],
                verbose_name="Código postal",
            ),
            preserve_default=False,
        ),
    ]
