# Generated by Django 4.2.7 on 2023-12-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motosaurio", "0003_alter_miusuario_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="miusuario",
            name="delivery_type",
            field=models.TextField(
                choices=[["D", "A domicilio"], ["R", "Recoger en tienda"]],
                null=True,
                verbose_name="Tipo de envío",
            ),
        ),
        migrations.AddField(
            model_name="miusuario",
            name="tipo_pago",
            field=models.TextField(
                choices=[["Cr", "Contrareembolso"], ["T", "Tarjeta"]],
                null=True,
                verbose_name="Tipo de pago",
            ),
        ),
    ]
