# Generated by Django 4.2.7 on 2023-12-07 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("motosaurio", "0004_miusuario_delivery_type_miusuario_tipo_pago"),
    ]

    operations = [
        migrations.RenameField(
            model_name="miusuario",
            old_name="tipo_pago",
            new_name="payment_type",
        ),
    ]
