# Generated by Django 4.1.13 on 2023-12-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "email",
                    models.CharField(max_length=200, verbose_name="Correo elecrónico"),
                ),
                (
                    "direccion",
                    models.CharField(max_length=200, verbose_name="Dirección postal"),
                ),
                (
                    "telefono",
                    models.BigIntegerField(null=True, verbose_name="Teléfono"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=500, verbose_name="Sobre nosotros"),
                ),
            ],
        ),
    ]
